### ISSUE TITLE
Sudden loss in latency

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#12]
So, I'll be using it for a bit, and having a 99 percentile latency in the vision API of 1000ms. Then suddenly it will take 10s of seconds to finish a translation, if it finishes at all. But I don't seem to see anything wrong in the cloud console.

I'm not sure what the issue is.

**Comment by SethRobinson** [comment]
Hmm.  I've not seen this behavior.  If anyone has a way to replicate it please post.

**Comment by SethRobinson** [comment]
I saw some weird stuff like that today, like it would be stuck at "30 translations left" or whatever, and then after like 5 to 10 seconds they would all instantly clear.  Not sure what the deal was, it seemed to fix itself a bit later.

**Comment by SethRobinson** [comment]
Update:  This was caused by a bug in the text construction engine that was stuck doing a ton of math in certain situations, will be fixed in next commit!
