### ISSUE TITLE
Feature Request: More customizable hotkeys

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#14]
Some of the hotkeys are customizable, but others do not seem to be.

Right now, using this requires one hand on a controller, and the other using the keyboard to press "Space" to close the translation. I'd like to be able to override that hot key in particular so that I don't need to use the keyboard at all while playing.

**Comment by SethRobinson** [comment]
Thanks.  Recent versions now also map the "do translation toggle" to be mapped to the controller and smoothly work simultaneously with the game/emulator using the same joystick.   So controller only gameplay + translation is now possible.  (Hint, if you set a rect region by keyboard first, it will default to using that region only)

By default, it's pushing down (as in the button click) on the left stick, but this can be configured in the config.txt.

Note:  Only gamepads that support xinput can do this, like the Xbox control pads.  (360, xb1, etc)
