### ISSUE TITLE
re-triggerable box capture

### ISSUE THREAD

**Issue by coltonoscopy** [SethRobinson/UGT#19]
Hey Seth, sorry for bombarding you :) This one's more of a feature request!

Typically (as I know you know) with many RPGs, the dialogue box is always in the same place. Being able to assign a box once and then recapture it with the exact same placement/dimensions with a hotkey rather than redrawing it would be super useful. (If this is already a feature, I apologize; wasn't able to find!)

An acceptable response to this (on the surface) might be to say that one can just capture the whole screen repeatedly with the hotkey that already exists for that, but there are some games which have tons of text on the screen besides the dialogue we might want to translate (Final Fantasy XIV Online comes to mind immediately, since that's what I've been often playing), and I have to assume this will unnecessarily query and fetch from Google's APIs, on top of just making things like the HTML export muddier than they would be with just a simple limited recapture of a certain part of the screen that only contains the desired text in question.

Let me know what your thoughts are; Capture2Text, another (less effective) OCR screen capture solution had a feature like this that would have been killer had their program actually had good OCR, but they use something local that does a pretty poor job with large text blocks, so I hardly use that feature :)

**Comment by SethRobinson** [comment]
Hey Colton,

This feature does already exist if I'm understanding correctly - after
setting a custom rect (alt-f10?), the "capture active window" button
(ctrl-f12)  (or capture button on the gamepad) will use only the rect area
that was previously set, works well for hitting just a dialog box
repeatedly, no need to keep setting the rect size.

Seth A. Robinson
www.rtsoft.com

**Comment by coltonoscopy** [comment]
Ahh, yes! You are correct :) It wasn't clear to me that continuing to use the rect following the initial usage would adopt this behavior; should have experimented just in case, to be honest! Thanks for the response!! (and thanks for having implemented this in advance ;)
