### ISSUE TITLE
UGT churns CPU while in idle foreground

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#21]
Reproduction steps:

0) Open your system CPU monitor, and have a game running.
1) Notice CPU is at 10% utilization
2) perform a window translation of a 1920 x 1080 sized window.
3) Wait for the translation to complete. Keep the translation in the foreground
4) Notice the game is stuttering. CPU Utilization now at 29%
5) Alt-tab to your system monitor. Notice the CPU utilization immediately drops back to 10%
6) Alt-tab back to UGT. System utilization again jumps to 29%

Expected Result:
There is no reason for UGT to be churning through 20% of my CPU while idle.

**Comment by Meerkov** [comment]
Note that this may be GPU, as my current system has integrated graphics.

**Comment by Meerkov** [comment]
It looks like the problem is that UGT has no frame limit by default. this results in significant churn.

Also, the FPS limit code doesn't work correctly. Please try this patch to main.cpp

```c++
if (g_fpsLimit != 0)
		{
			double currSystemTime = GetSystemTimeAccurate();
			while (fpsTimer > currSystemTime)
			{
				Sleep(1);
				currSystemTime = GetSystemTimeAccurate();
			}
			fpsTimer = currSystemTime +(1000.0/ (double(g_fpsLimit)));
		}
```

Edit: And consider an arbitrary default of maybe 100 FPS. Most monitors likely only support 60 FPS anyway.

**Comment by SethRobinson** [comment]
Thanks will check this out for the next version.

**Comment by SethRobinson** [comment]
Changes applied, thanks!   (note: these changes are on github only right now, not a 'real' release)
