### ISSUE TITLE
Default JPG Quality is 100, should be lower

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#23]
JPG Quality in the config is set to 100 by default. This increases the file size, and thus the time it takes to save and transfer the file. The config recommends 95 at most, but the default is 100.

The default should be optimized for common use-cases, which means speed of translation should be prioritized.

Example file sizes:
Quality | Size
100 = 146 KB
95 = 86 KB
90 = 66 KB
85 = 52 KB
80 = 46 KB

Attached is a diff of two screenshots: One done at 100 and one at 80. You can see the difference is a rectangular section which shows some more grayish color pixels. This is the text being translated. (black pixels = no difference)

![Diff](https://user-images.githubusercontent.com/8139496/115819343-81f93b00-a3b3-11eb-9781-4e6fe69469a1.png)
I found in my test that the translation changed a little at quality 95 and 90, and returned to the original translation at 85 and 80. This tells me that while the translation may change, it is unlikely that the quality is significantly impacting it (it is just as likely that the translation is wrong at 95% instead of at 80%).

I recommend a default of 85%. This would represent a 3x speedup in saving and sending the file. When performing a full screen translation of 1920x1080, the savings represents at a noticeable amount of time on every transfer.

**Comment by SethRobinson** [comment]
Oops, will change the default.
