### ISSUE TITLE
FR: Remove all sound effects

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#25]
It doesn't make sense to play a sound on startup, for example. Or any other time, since every action already has visual indicators.

And though I'm not an expert, the audio indicator doesn't seem helpful for blind users either. it may even make it less accessible, since it's presumably more important to keep the audio channel clear of unnecessary sound effects.

**Comment by SethRobinson** [comment]
Hmm.  For my setup I appreciate the startup sound because it instantly lets me know my audio is routed correctly to hear the spoken dialog.  As for the sound on capture, I could go either way.

I believe you can achieve this now by starting it with the -nosound command line parm but that would also disable any text to speech.

**Comment by Meerkov** [comment]
Yeah, in my local copy I immediately removed the snapshot sound because I do recordings while using it, so that got annoying quickly. I haven't removed the startup sound yet, but it's probably the next one to go for me since it's just a little bit too long. I startup, and then I have to wait 5+ seconds for it to quiet down before hitting "record".

I figure, if it bothers me, it's probably worth mentioning as something other people might like too. I think a quick two note "boo-beep!", less than a second, is sufficient to tell you that the audio is working. But I acknowledge that making sure the audio is working is a legitimate reason for the startup sound.

**Comment by SethRobinson** [comment]
Startup sound changed to be shorter, added "Disable capture sound" checkbox to the in-app GUI  (note: these changes are on github only right now, not a 'real' release)
