### ISSUE TITLE
Multi detectedLanguage prefers last entry

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#31]
```c++
cJSON_ArrayForEach(detectedLanguage, detectedLanguages)
  {
    const cJSON *languageCode = cJSON_GetObjectItemCaseSensitive(detectedLanguage, "languageCode");
    textArea.language = languageCode->valuestring;
    //LogMsg("Found language %s", languageCode->valuestring);
  }
```

This code iterates over the detected languages, and chooses the language code that is the last entry.

I've seen for example, both a `ja` and `no` detected as languages with equal confidence. I'm not sure if multiple languages can appear with unequal confidence, but if so, it should preserve the most likely language. In the case of a tie, I think it should prefer the first entry.

**Comment by Meerkov** [comment]
Worth noting: I don't actually know if this causes any bugs, I just happened to notice it.

**Comment by SethRobinson** [comment]
Sounds good, changed so it breaks after the first language instead of the last
