### ISSUE TITLE
LastVerts Silly Code

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#32]
```c++
CL_Vec2f lastVerts[4];
	for (int i = 0; i < 4; i++)
	{
		lastVerts[0] = CL_Vec2f(0, 0);
	}
```

`i` is not used in the loop, so this just initializes lastVerts[0] four times instead. This looks like a mistake.
In GameLogicComponent line ~175

**Comment by SethRobinson** [comment]
Oops, fixed!  Thanks.
