### ISSUE TITLE
DeepL api free/paid

### ISSUE THREAD

**Issue by RandomTemere** [SethRobinson/UGT#36]
Current DeepL request in TextAreaComponant.cpp only pings the free api link (https://api-free.deepl.com)
Does not allow paid DeepL users to connect their api (https://api.deepl.com)

If possible another option to allow the DeepL translation request to swap between the free and paid links based on user config, would be appreciated. Sometimes 500k/month characters isn't enough...

**Comment by SethRobinson** [comment]
Oops, didn't realize that was a thing, will add to the config.txt.

**Comment by SethRobinson** [comment]
Thanks, added for the 0.72 release!  2b029f8a
