### ISSUE TITLE
UGT Freeze

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#38]
Trying to translate this image results in a freeze for me with "2 translations remaining" showing.

![crash](https://user-images.githubusercontent.com/8139496/130704631-e08eafc3-ca3a-4aa4-bd18-71d0374f0f8e.png)

**Comment by SethRobinson** [comment]
Thanks!  Fixed in 2b029f8a

More info:

Google translated some of the numbers as upside down text - (57 become L5 for example) and UGT did a very bad job of handling rotated text boxes - now it should properly display (and not freeze) for text rotated at any angle.
