### ISSUE TITLE
High CPU and Power Consumption

### ISSUE THREAD

**Issue by ghost** [SethRobinson/UGT#48]
### Discussed in https://github.com/SethRobinson/UGT/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **yasumitsuru** February 12, 2023</sup>
When using UGT in the background it consumes a lot of CPU and energy
CPU +14% on core i7 770k

https://1drv.ms/u/s!AvGHC8J8HU3Ljt0AEPLp3RGQXGxJsg?e=ca7ZiH</div>

**Comment by SethRobinson** [comment]
Hmm, it should be sitting in a loop with a sleep() (doing no rendering at all), so either there is a bug or task manager might be giving weird results because the cores are being unused or something. 

I'll check it next time I'm working on UGT

**Comment by lllmio** [comment]
I also have high CPU usage. Thought it's supposed to be like that...
20-30% on AMD Ryzen 3 1200. Have to turn off UGT during PVP because of noticeable slowdowns
had similar numbers on Intel Core i7 4th gen laptop before
![Screenshot 2023-03-02 214833 cut](https://user-images.githubusercontent.com/1689966/222550337-b8753356-6132-4d9e-b7ab-9ee54da40520.png)

**Comment by SethRobinson** [comment]
Hmm, I'm getting between 2 and 3% right now it looks like but yeah, something is weird:

![image](https://user-images.githubusercontent.com/394547/222563015-0634a68a-8634-4919-9707-0524098b1270.png)

When I move my mouse fast in circles over its window, CPU usage when down to 0.3%?  Why would extra mouse message processing in the app cause that to happen? 

![image](https://user-images.githubusercontent.com/394547/222564010-6d8a69ce-4025-4a5f-b2bf-d2d3c5ded87c.png)

And when I minimize, it goes back up to 3%.  I would expect near 0% when minimized.  I'll see if I can figure out what I'm doing wrong.

**Comment by SethRobinson** [comment]
Ok, I think I fixed it - I'm now seeing lower CPU rates when in use and it drops to 0% when in the background. 

Please [give V0.75 a shot](https://www.rtsoft.com/files/UniversalGameTranslator_Windows.zip) and let me know if this fixes stuff!

**Comment by lllmio** [comment]
thanks!
yes, 0% in background. will put it in autostart now
p.s: and thank again for the app! I use it a lot to combine learning language with playing. got quite some bills from google for that 😅
