### ISSUE TITLE
Right joystick button (and any gamepad button) no longer works 

### ISSUE THREAD

**Issue by Cloudstrifeff7** [SethRobinson/UGT#53]
Good morning!
I have often used your program without problems, using the right joystick button on my Xbox One controller to translate but after a few months of not using it I today found that the gamepad on any button no longer works. I also tried with another xbox one controller and I have the same problem, but in games they work perfectly. I now do not know if it is caused by some Windows 11 update but I am using its latest version.

I attach the log file here.

[log.txt](https://github.com/SethRobinson/UGT/files/11402968/log.txt)

I now don't know what it is caused by and hopefully it will be fixed.

Thanks in advance!

**Comment by SethRobinson** [comment]
Thanks, I actually just tried it earlier today before reading this (Xbox elite) and had the same issue.  Not sure what's up.  Will check it out for the next version.

**Comment by Cloudstrifeff7** [comment]
> Thanks, I actually just tried it earlier today before reading this (Xbox elite) and had the same issue. Not sure what's up. Will check it out for the next version.

Perfect, thanks!

**Comment by lllmio** [comment]
ended up using AutoHotkey script as workaround, e.g. to send Ctrl+Q from right shoulder button of Xbox 360 controller:

`Joy6::Send ^q  ;`

**Comment by cpod12** [comment]
> Thanks, I actually just tried it earlier today before reading this (Xbox elite) and had the same issue. Not sure what's up. Will check it out for the next version.

have you figured anything out for this? i'd be down to take a look for fixing this, but i'm unsure how to get started

**Comment by SethRobinson** [comment]
Your comment got me off my butt, thanks.  Fixed it today, it should prompt you to update if you run it.
