### ISSUE TITLE
Will not work due to scaling on Windows 10

### ISSUE THREAD

**Issue by alexanderubieta** [SethRobinson/UGT#9]
First off, thank you for making this useful program. I had the same idea to make this with google translate for a japanese game I am playing , but found yours already existed which was a nice surprise.

I am using a laptop with a 4k screen with the resolution set at 3840x2160 for my computer. Windows applies recommended scaling to 250% for desktop items such as windows, icons, and tasks. When I use UGT in desktop mode and select the current window, entire desktop, or an area on the screen, it doesn't translate the real area it should. It is always off to the corner of the window I'm in or just the top left corner of the entire desktop. When I change the Windows scaling preference to 100% for my resolution, it works correctly. 

Is there anything that could be done to address this issue without having to change my laptop's resolution or scaling to make UGT work?

**Comment by SethRobinson** [comment]
Sorry for the slow reply, have not had a chance to address this issue but hope to in the future.

**Comment by SethRobinson** [comment]
This has been fixed in the latest version.
